export default [
  { numeric: 1, spelled: 'One' },
  { numeric: 2, spelled: 'Two' },
  { numeric: 3, spelled: 'Three' },
  { numeric: 4, spelled: 'Four' },
  { numeric: 5, spelled: 'Five' },
  { numeric: 6, spelled: 'Six' },
  { numeric: 7, spelled: 'Seven' },
  { numeric: 8, spelled: 'Eight' },
  { numeric: 9, spelled: 'Nine' },
  { numeric: 10, spelled: 'Ten' },
  { numeric: 11, spelled: 'Eleven' },
  { numeric: 12, spelled: 'Twelve' },
  { numeric: 13, spelled: 'Thirteen' },
  { numeric: 14, spelled: 'Fourteen' },
  { numeric: 15, spelled: 'Fifteen' },
  { numeric: 16, spelled: 'Sixteen' },
  { numeric: 17, spelled: 'Seventeen' },
  { numeric: 18, spelled: 'Eighteen' },
  { numeric: 19, spelled: 'Nineteen' },
  { numeric: 20, spelled: 'Twenty' }
];
